site_name: express-openapi-validator
theme:
  # logo: assets/logo.png
  icon:
    logo: fontawesome/solid/check-double
  name: material
  palette:
    scheme: slate
    # primary: indigo
  features:
    # - navigation.sections
    # - navigation.tracking
    - content.tabs.link
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.expand
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - index.md
  - Getting started: 
    - gc-installation.md
    - gc-quick-start.md 
    - gc-guides.md
    - faq.md

  - Reference:
    - Docs:
      - ref-base-url.md
      - ref-security-handlers.md
      - Operation Handlers: guide-operation-handlers.md
      - Multiple API Specs: guide-multiple-specs.md
      - validation-curl.md
    - Options:
      - usage-options-summary.md
      - usage-api-spec.md
      - usage-validate-requests.md
      - usage-validate-responses.md
      - usage-validate-security.md
      - usage-validate-api-spec.md
      - usage-formats.md
      - usage-unknown-formats.md
      - usage-serdes.md
      - usage-operation-handlers.md
      - usage-ignore-paths.md
      - usage-ignore-undocumented.md
      - usage-file-uploader.md
      - usage-ref-parser.md
      - usage-coerce-types.md
    
  - Guides:
    - Standard API Server: guide-standard.md
    - Operation Handlers: guide-operation-handlers.md
    - Multiple API Specs: guide-multiple-specs.md

  - About:
    - license.md
    - about-who-are-we.md

extra:
  analytics:
    provider: google
    property: G-SZZ6RXH2FY